target("nonlib")
    set_kind("shared")
    add_files("nonlib/*.C")
    add_includedirs("nonlib")
    add_sysincludedirs("/usr/local/include/ntk")
    add_sysincludedirs("/usr/include/sigc++-2.0")
    add_sysincludedirs("/usr/lib/x86_64-linux-gnu/sigc++-2.0/include")
    
target("FL")
    set_kind("static")
    add_files("FL/*.C")
    add_includedirs("nonlib")
    add_sysincludedirs("/usr/local/include/ntk")
    add_sysincludedirs("/usr/include/sigc++-2.0")
    add_sysincludedirs("/usr/lib/x86_64-linux-gnu/sigc++-2.0/include")
    
target("non-sequencer")
    set_kind("binary")
    add_files("src/*.C")
    add_deps("nonlib", "FL")
    add_includedirs("nonlib")
    add_includedirs("FL")
    add_sysincludedirs("/usr/local/include/ntk")
    add_sysincludedirs("/usr/include/sigc++-2.0")
    add_sysincludedirs("/usr/lib/x86_64-linux-gnu/sigc++-2.0/include")
